# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nilpa Jha
tagline:          'Nilpa Jha'
description:      'Check below link for my github repo or catch me on twitter <a href="https://twitter.com/nsquare_kolu" target="_blank">@nsquare_kolu</a> or <a href="https://www.linkedin.com/in/nilpajha/" target="_blank">Nilpa Jha @LinkedIn</a>.'
url:                       
baseurl:          /

author:
  name:           
  url:            https://nsquare.github.io/

paginate:         2


# Custom vars
version:          1.1.2

github:
  repo:           https://github.com/nsquare

gems:
                  - jekyll-seo-tag  
# comments: true
